### ISSUE TITLE
UI language

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-frontend#4]
I saw in one of the last commits ( d76dee48aa) that the gettext keys were changed to german. This in fact makes the default language of the UI german for the moment, but we agreed on the Konsortialmeeting to have english gettext msgs/keys (because we are an open source project, they are shorter and so on) and have german translations in the .mo/.po files.

**Comment by bdf-net** [comment]
The message keys were changed to german in order to have a _working_ UI from the start.
While I agree that english message-keys are best practice, the switch to german has practical reasons:
Since backmeup is a project based in Austria we need a german interface. In this sense, I'd rather have an interface in german and translate to english (if needed), than have an english interface on an austrian-based project that might never get translated.
Also, I don't see why english message-keys are (per se) shorter (or why shorter keys would be a benefit)?

**Comment by RolandLehner** [comment]
As we agreed at our meeting in the end of september, the language in the code has to be english, the user interface should be in german. 
BackMeUp is an open source project and intends to be a project that can be used and developed all over the world. OpenSource is our business model. English is the only language for OpenSource projects and is a must have in the code.

**Comment by bdf-net** [comment]
message keys were changed to english and we will take care of the german translation
