### ISSUE TITLE
Display icons at datasource/datasink selection

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-frontend#6]
Redesign datasource/datasink selection to display the available options with nice icons etc.

**Comment by fetzig** [comment]
nice icons? get no "nice icons" from rest api, thus cant supply enduser with nice icons in ui :(

**Comment by WolfgangEibner** [comment]
In the last meeting we agreed on having the icons stored in the frontend and matched by the datasink/-source identifier (plugin name?). Thus no icon is needed in the rest call anymore and showing the icons should be a UI only thing. It should be somehow done like internationalization.
One thing left open was: Who will design default icons for datasinks/-sources not having an own icon? BDF or GTN?

**Comment by bdf-net** [comment]
In order to display matching icons to the various data-sources/-sinks we need the aforementioned identifiers (plugin-names), which should read like e.g. "Dropbox" or "dropbox" (instead of "BackMeUp Dropbox Plug-In").
Concerning your inquiry about datsinks/-sources not having an own icon: right now we have the following options:
Discmailing Dropbox SkyDrive ZIP-Download Twitter Mail Facebook Moodle.
Providing icons for these options shouldn't be a problem. 
If however new datasources/-sinks can be added at any time, there will obviously be no icon for these (or a blank default icon) and the User Interface will get messy.

**Comment by fetzig** [comment]
- path to icons
- icons have filename like "org.backmeup.plugins.dropbox_128x128.png"...

**Comment by WolfgangEibner** [comment]
Default icons for datasources/-sinks exist already. We should design icons for already present plugins like Facebook datasource etc.
